import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/components/ClientProvider/ClientProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/auth";
import store from "@/store";
import InitialStateManager from "@/components/InitialStateManager/InitialStateManager";

// Load Google Fonts
const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });

export const metadata = {
  title: "Creator Catalyst",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Fetch session server-side
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProvider>
          {/* Initialize app state once here */}
          <InitialStateManager session={session} />

          {/* Common layout (Navbar, Footer, etc.) */}
          {/* <Navbar /> */}

          {/* Page content */}
          {children}

          {/* <Footer /> */}
        </ClientProvider>
      </body>
    </html>
  );
}
